name: Nightly
on:
  schedule:
    - cron: '0 3 * * *'

env:
  COMPOSER_AUTH: ${{ secrets.COMPOSER_GITHUB_AUTH }}

jobs:
  test-next:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup PHP with Composer v1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1

      - name: Authenticate npm
        env:
          COMPOSER_GITHUB_TOKEN: ${{ secrets.COMPOSER_GITHUB_TOKEN }}
        run: |
          npm config set "@leviy:registry" "https://npm.pkg.github.com" \
          && npm config set "//npm.pkg.github.com/:_authToken" "$COMPOSER_GITHUB_TOKEN"

      - name: Composer Install
        run: composer install --no-interaction --no-progress --no-ansi

      - name: Npm Install
        run: npm install --silent --no-fund --no-audit

      - name: Test
        run: make static-analysis unit-tests acceptance-tests

  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup PHP with Composer v1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1

      - name: Authenticate npm
        env:
          COMPOSER_GITHUB_TOKEN: ${{ secrets.COMPOSER_GITHUB_TOKEN }}
        run: |
          npm config set "@leviy:registry" "https://npm.pkg.github.com" \
          && npm config set "//npm.pkg.github.com/:_authToken" "$COMPOSER_GITHUB_TOKEN"

      - name: Security checks
        run: make security-tests
