name: Test
on: push

env:
  COMPOSER_AUTH: ${{ secrets.COMPOSER_GITHUB_AUTH }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.3 ]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer Install
        uses: ramsey/composer-install@v2

      - name: Test
        run: make static-analysis unit-tests acceptance-tests coding-standards

      - name: Integration tests
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          make integration-tests
